services:
    octante.docker_compose_yml_builder:
        class: Octante\DockerComposeBundle\Services\DockerComposeYmlBuilder

    octante.docker_compose_service_definition_builder:
            class: Octante\DockerComposeBundle\Services\DockerComposeServiceDefinitionBuilder

    octante.docker_compose_yml_plain:
        class: Octante\DockerComposeBundle\Services\DockerComposeYmlPlain